### PR TITLE
Setting default node_instantiation mpls value to 0

### PR DESCRIPTION
**Pull request by jonstout**
We expect migration from openflow to netconf to be a manual
process. Setting this as true while other required fields are null,
could result in undesired behavior.

### CODE REVIEW

**Comment by zec** [comment]
The basic idea of the changes looks reasonable. A couple of things, though:

* You should make the same change to the schema in perl-lib/OESS/share/nddi.sql that you did to [perl-lib/OESS/share/upgrade/oess-1.1.9-1.2.0](https://github.com/GlobalNOC/OESS/pull/428/files#diff-b9a9015fb5bb584962643dbe2173c035R54).
* I'm not familiar with the UI code, so this may not be relevant, but is there a reason you're only checking for undefined [in circuit_details_box.js](https://github.com/GlobalNOC/OESS/pull/428/files#diff-0cb366d42a55820418ee10e1d9375c78R65) and not also for null?

**Comment by zec** [comment]
One question, as well: is there a reason why the `openflow` and `mpls` fields in `node_instantiation` aren't set to be `NOT NULL`?

**Comment by zec** [comment]
(That last question _may_ be out of scope for this pull request, AFAIK, but it seems worth asking.)

**Comment by jonstout** [comment]
I've updated oess-1.1.9-1.2.0 to reflect your request, and went ahead and added `NOT NULL` too. There are plenty of places that expect a real value, and I can't guarantee we would handle null values correctly in all cases.

As for the UI change, that's left over from some of AJ's work. I'm not sure what it's purpose was other than to ensure a later page in the circuit creation workflow is rendered correctly.

**Pull request merged**
