### PR TITLE
Several issues that we have been testing but didn't have commited

### PR DESCRIPTION
**Pull request by ajragusa**

### CODE REVIEW

**Comment by zec** [comment]
The changes in OESS::Database and the upgrade script look good.

For OESS::NSI::MessageQueue, it looks like the schema's still wrong - you'd want to take a look at the code around [line 192 in OESS::Notification](https://github.com/GlobalNOC/OESS/blob/2d81cd0c563ef626685063f0648c95bfada9cbd3/perl-lib/OESS/lib/OESS/Notification.pm#L192), as that's what's generating the messages that are being consumed.

I don't know enough to really evaluate the changes under OESS::MPLS.

**Comment by ajragusa** [comment]
@zec ok those should be fixed!

**Comment by zec** [comment]
The 'circuit' parameter of the message is _not_ an integer - it's an enhanced version of the circuit record from the DB (e.g., [[1]](https://github.com/GlobalNOC/OESS/blob/2d81cd0c563ef626685063f0648c95bfada9cbd3/frontend/webservice/provisioning.cgi#L814) [[2]](https://github.com/GlobalNOC/OESS/blob/2d81cd0c563ef626685063f0648c95bfada9cbd3/app/oess_scheduler.pl#L151)).

**Comment by zec** [comment]
OESS::NSI::MessageQueue and OESS::NSI::Processor look good at this point - we'll want to actually test this, of course, but I don't see any issues off-hand.

**Pull request merged**
